### ISSUE TITLE
vehicle_odometer

### ISSUE THREAD

**Issue by iannak** [Escodoo/fleet-addons#14]
![Captura de tela de 2022-03-18 15-00-04](https://user-images.githubusercontent.com/63086797/159058305-90745a33-34e0-4981-851d-779384a3bf09.png)

error 500 no POST ou seja ele ainda não está cadastrando e falta adicionar mais campos

**Comment by marcelsavegnago** [comment]
Confere no modelo de dados do Odoo fleet.vehicle.odometer se tem estes campo modelo do veiculo e o active.

Outra coisa no log do Odoo tem mais detalhes sobre o problema. Dá uma olhada que provavelmente deve ta sinalizando erro com algum campo destes que citei.

**Comment by iannak** [comment]
Done #14
