### ISSUE TITLE
[14.0][RFC] Em fleet.vehicle.service adicionar state_id como filtro

### ISSUE THREAD

**Issue by marcelsavegnago** [Escodoo/fleet-addons#37]
No datamodel fleet.vehicle.serach.input já foi implementado o campo, mas falta implementar o filtro.
https://github.com/Escodoo/fleet-addons/blob/e23c20130d9ea1ce7de4f377998044a7f6da9dbe/fleet_rest_api/datamodels/fleet_vehicle_datamodels.py#L92

Enfim, deve ser implementado logo abaixo da desta linha
https://github.com/Escodoo/fleet-addons/blob/e23c20130d9ea1ce7de4f377998044a7f6da9dbe/fleet_rest_api/services/fleet_vehicle_services.py#L122

**Comment by iannak** [comment]
feito #37
